package utils

import (
	"github.com/chyroc/lark"
)

func CodeLanguage(l interface{}) string {
	var lan lark.DocxCodeLanguage
	switch ll := l.(type) {
	case string:
		lan = languageStr2Enum[ll]
	case lark.DocxCodeLanguage:
		lan = ll
	}
	return languageEnum2markdownStr[lan]
}

var languageStr2Enum = map[string]lark.DocxCodeLanguage{
	"Plain Text":        lark.DocxCodeLanguagePlainText,
	"ABAP":              lark.DocxCodeLanguageABAP,
	"Ada":               lark.DocxCodeLanguageAda,
	"Apache":            lark.DocxCodeLanguageApache,
	"Apex":              lark.DocxCodeLanguageApex,
	"Assembly language": lark.DocxCodeLanguageAssembly,
	"Bash":              lark.DocxCodeLanguageBash,
	"C":                 lark.DocxCodeLanguageCSharp,
	"C#":                lark.DocxCodeLanguageCPlusPlus,
	"C++":               lark.DocxCodeLanguageC,
	"COBOL":             lark.DocxCodeLanguageCOBOL,
	"CSS":               lark.DocxCodeLanguageCSS,
	"CoffeeScript":      lark.DocxCodeLanguageCoffeeScript,
	"D":                 lark.DocxCodeLanguageD,
	"Dart":              lark.DocxCodeLanguageDart,
	"Delphi":            lark.DocxCodeLanguageDelphi,
	"Dockerfile":        lark.DocxCodeLanguageDjango,
	"Django":            lark.DocxCodeLanguageDockerfile,
	"Erlang":            lark.DocxCodeLanguageErlang,
	"Fortran":           lark.DocxCodeLanguageFortran,
	"FoxPro":            lark.DocxCodeLanguageFoxPro,
	"Go":                lark.DocxCodeLanguageGo,
	"Groovy":            lark.DocxCodeLanguageGroovy,
	"HTML":              lark.DocxCodeLanguageHTML,
	"HTMLBars":          lark.DocxCodeLanguageHTMLBars,
	"HTTP":              lark.DocxCodeLanguageHTTP,
	"Haskell":           lark.DocxCodeLanguageHaskell,
	"JSON":              lark.DocxCodeLanguageJSON,
	"Java":              lark.DocxCodeLanguageJava,
	"JavaScript":        lark.DocxCodeLanguageJavaScript,
	"Julia":             lark.DocxCodeLanguageJulia,
	"Kotlin":            lark.DocxCodeLanguageKotlin,
	"LaTeX":             lark.DocxCodeLanguageLateX,
	"Lisp":              lark.DocxCodeLanguageLisp,
	"Logo":              lark.DocxCodeLanguageLogo,
	"Lua":               lark.DocxCodeLanguageLua,
	"MATLAB":            lark.DocxCodeLanguageMATLAB,
	"Makefile":          lark.DocxCodeLanguageMakefile,
	"Markdown":          lark.DocxCodeLanguageMarkdown,
	"Nginx":             lark.DocxCodeLanguageNginx,
	"Objective-C":       lark.DocxCodeLanguageObjective,
	"OpenEdge ABL":      lark.DocxCodeLanguageOpenEdgeABL,
	"PHP":               lark.DocxCodeLanguagePHP,
	"Perl":              lark.DocxCodeLanguagePerl,
	"PostScript":        lark.DocxCodeLanguagePostScript,
	"PowerShell":        lark.DocxCodeLanguagePower,
	"Prolog":            lark.DocxCodeLanguageProlog,
	"ProtoBuf":          lark.DocxCodeLanguageProtoBuf,
	"Python":            lark.DocxCodeLanguagePython,
	"R":                 lark.DocxCodeLanguageR,
	"RPG":               lark.DocxCodeLanguageRPG,
	"Ruby":              lark.DocxCodeLanguageRuby,
	"Rust":              lark.DocxCodeLanguageRust,
	"SAS":               lark.DocxCodeLanguageSAS,
	"SCSS":              lark.DocxCodeLanguageSCSS,
	"SQL":               lark.DocxCodeLanguageSQL,
	"Scala":             lark.DocxCodeLanguageScala,
	"Scheme":            lark.DocxCodeLanguageScheme,
	"Scratch":           lark.DocxCodeLanguageScratch,
	"Shell":             lark.DocxCodeLanguageShell,
	"Swift":             lark.DocxCodeLanguageSwift,
	"Thrift":            lark.DocxCodeLanguageThrift,
	"TypeScript":        lark.DocxCodeLanguageTypeScript,
	"VBScript":          lark.DocxCodeLanguageVBScript,
	"Visual Basic":      lark.DocxCodeLanguageVisual,
	"XML":               lark.DocxCodeLanguageXML,
	"YAML":              lark.DocxCodeLanguageYAML,
}

var languageEnum2markdownStr = map[lark.DocxCodeLanguage]string{
	lark.DocxCodeLanguagePlainText:    "",
	lark.DocxCodeLanguageABAP:         "abap",
	lark.DocxCodeLanguageAda:          "ada",
	lark.DocxCodeLanguageApache:       "apache",
	lark.DocxCodeLanguageApex:         "apex",
	lark.DocxCodeLanguageAssembly:     "assembly",
	lark.DocxCodeLanguageBash:         "bash",
	lark.DocxCodeLanguageCSharp:       "csharp",
	lark.DocxCodeLanguageCPlusPlus:    "cpp",
	lark.DocxCodeLanguageC:            "c",
	lark.DocxCodeLanguageCOBOL:        "cobol",
	lark.DocxCodeLanguageCSS:          "css",
	lark.DocxCodeLanguageCoffeeScript: "coffeescript",
	lark.DocxCodeLanguageD:            "d",
	lark.DocxCodeLanguageDart:         "dart",
	lark.DocxCodeLanguageDelphi:       "delphi",
	lark.DocxCodeLanguageDjango:       "django",
	lark.DocxCodeLanguageDockerfile:   "dockerfile",
	lark.DocxCodeLanguageErlang:       "erlang",
	lark.DocxCodeLanguageFortran:      "fortran",
	lark.DocxCodeLanguageFoxPro:       "foxpro",
	lark.DocxCodeLanguageGo:           "go",
	lark.DocxCodeLanguageGroovy:       "groovy",
	lark.DocxCodeLanguageHTML:         "html",
	lark.DocxCodeLanguageHTMLBars:     "htmlbars",
	lark.DocxCodeLanguageHTTP:         "http",
	lark.DocxCodeLanguageHaskell:      "haskell",
	lark.DocxCodeLanguageJSON:         "json",
	lark.DocxCodeLanguageJava:         "java",
	lark.DocxCodeLanguageJavaScript:   "javascript",
	lark.DocxCodeLanguageJulia:        "julia",
	lark.DocxCodeLanguageKotlin:       "kotlin",
	lark.DocxCodeLanguageLateX:        "latex",
	lark.DocxCodeLanguageLisp:         "lisp",
	lark.DocxCodeLanguageLogo:         "logo",
	lark.DocxCodeLanguageLua:          "lua",
	lark.DocxCodeLanguageMATLAB:       "matlab",
	lark.DocxCodeLanguageMakefile:     "makefile",
	lark.DocxCodeLanguageMarkdown:     "markdown",
	lark.DocxCodeLanguageNginx:        "nginx",
	lark.DocxCodeLanguageObjective:    "objectivec",
	lark.DocxCodeLanguageOpenEdgeABL:  "openedge-abl",
	lark.DocxCodeLanguagePHP:          "php",
	lark.DocxCodeLanguagePerl:         "perl",
	lark.DocxCodeLanguagePostScript:   "postscript",
	lark.DocxCodeLanguagePower:        "powershell",
	lark.DocxCodeLanguageProlog:       "prolog",
	lark.DocxCodeLanguageProtoBuf:     "protobuf",
	lark.DocxCodeLanguagePython:       "python",
	lark.DocxCodeLanguageR:            "r",
	lark.DocxCodeLanguageRPG:          "rpg",
	lark.DocxCodeLanguageRuby:         "ruby",
	lark.DocxCodeLanguageRust:         "rust",
	lark.DocxCodeLanguageSAS:          "sas",
	lark.DocxCodeLanguageSCSS:         "scss",
	lark.DocxCodeLanguageSQL:          "sql",
	lark.DocxCodeLanguageScala:        "scala",
	lark.DocxCodeLanguageScheme:       "scheme",
	lark.DocxCodeLanguageScratch:      "scratch",
	lark.DocxCodeLanguageShell:        "shell",
	lark.DocxCodeLanguageSwift:        "swift",
	lark.DocxCodeLanguageThrift:       "thrift",
	lark.DocxCodeLanguageTypeScript:   "typescript",
	lark.DocxCodeLanguageVBScript:     "vbscript",
	lark.DocxCodeLanguageVisual:       "vbnet",
	lark.DocxCodeLanguageXML:          "xml",
	lark.DocxCodeLanguageYAML:         "yaml",
}
